### PR TITLE
User interface

### PR DESCRIPTION
**Pull request by epinczinger**
User interface, user and board classes created.
Basic game flow created.

### CODE REVIEW

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey Team  :wave:
-
You have done a splendid job! :tada: 
We, however, do have some few changes to carry out before we proceed (see review comment).
##
### Behaviour
#### We need to make sure the basic game flow is prepared as follows 👇 : ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [x] Make sure the `main.rb` uses `puts/print` and `get.chomp` commands. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/main_rb.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)).
- [x] `[OPTIONAL]` game asks players for their names.
- [x] `[REQUIRED]` game tells which player turn it is
- [x] `[REQUIRED]` game asks the player to select from available moves
- [x] `[REQUIRED]` game informs the player if the selected move is invalid
- [x] `[REQUIRED]` game displays board after the player move
- [x] `[REQUIRED]` game informs the player if the selected move is a winning move
- [x] `[REQUIRED]` game informs player if the selected move is a draw move
- [x] `[REQUIRED]` game repeats all actions for the next player's move

### Implementation details
* [x] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
* [x] Inside the loop, you should call actions repeated for each move
* [x] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:
```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move
  
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```
##
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Review by Dandush03 — COMMENTED** [review]
# Status: 🔴 Required Changes 🔴 

### Great Work on your project

### There are some changes required to get approved.

 - [x] Right now your wining validation isn't working 
> Capture
> It doesn't inform that this was a winning move and it didn't finish the loop
> The game only ends on a draw right now.

> Quoting my college; -"[REQUIRED] game informs the player if the selected move is a winning move"

# [__OPTIONAL__]

- [x] Great work using colorized gem and upgrading your readme file, however, it's a bad practice to make use of a gem without a Gemfile [for more info check this link](https://guides.rubygems.org/rubygems-basics/)

- [x] Since you already made uses of class, I will strongly advise you to reconsider using attr_accessor since you won't be able to continue in the next milestone if you make use of them unnecessarily.

## Beside this, you've made a great job applying the requested changes, keep up the good work 💪 

# Happy Coding 🤓 💻

**Comment by epinczinger** [comment]
Requested changes have been done.

Winner def completed.
Gemfile added.
Attr_accesor removed from classes.

**Comment by gdumani** [comment]
- Changed User and Board Classes to remove direct user interaction. Now puts and gets are on the main routine only.

- Optimized logic in winner method in Board class.

- Added a valid status variable on the Board class to pass information for user interaction when an invalid input is rejected.

- removed the display method from Board. This task is now on main routine

**Review by lucasmazo32 — APPROVED** [review]
# Milestone approved :rocket:

#### Great job!

#### Your project looks great!

### You can go ahead and merge this pull request!

### Happy coding! :computer:

## Lucas Mazo

**Pull request merged**
